// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: ldap.adapter.v1.proto

package ldap_adapter_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseError_GrpcResponse int32

const (
	ResponseError_UNIVERSAL           ResponseError_GrpcResponse = 0
	ResponseError_BAD_PARAMETER       ResponseError_GrpcResponse = 400
	ResponseError_UNAUTORIZED         ResponseError_GrpcResponse = 401
	ResponseError_FORBIDDEN           ResponseError_GrpcResponse = 403
	ResponseError_NOT_FOUND           ResponseError_GrpcResponse = 404
	ResponseError_NOT_ACCEPTABLE      ResponseError_GrpcResponse = 406
	ResponseError_SERVER_ERROR        ResponseError_GrpcResponse = 500
	ResponseError_SERVICE_UNAVAILABLE ResponseError_GrpcResponse = 503
)

// Enum value maps for ResponseError_GrpcResponse.
var (
	ResponseError_GrpcResponse_name = map[int32]string{
		0:   "UNIVERSAL",
		400: "BAD_PARAMETER",
		401: "UNAUTORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		406: "NOT_ACCEPTABLE",
		500: "SERVER_ERROR",
		503: "SERVICE_UNAVAILABLE",
	}
	ResponseError_GrpcResponse_value = map[string]int32{
		"UNIVERSAL":           0,
		"BAD_PARAMETER":       400,
		"UNAUTORIZED":         401,
		"FORBIDDEN":           403,
		"NOT_FOUND":           404,
		"NOT_ACCEPTABLE":      406,
		"SERVER_ERROR":        500,
		"SERVICE_UNAVAILABLE": 503,
	}
)

func (x ResponseError_GrpcResponse) Enum() *ResponseError_GrpcResponse {
	p := new(ResponseError_GrpcResponse)
	*p = x
	return p
}

func (x ResponseError_GrpcResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseError_GrpcResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_ldap_adapter_v1_proto_enumTypes[0].Descriptor()
}

func (ResponseError_GrpcResponse) Type() protoreflect.EnumType {
	return &file_ldap_adapter_v1_proto_enumTypes[0]
}

func (x ResponseError_GrpcResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseError_GrpcResponse.Descriptor instead.
func (ResponseError_GrpcResponse) EnumDescriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{3, 0}
}

type ResponseError_ErrorCode int32

const (
	ResponseError_SUCCESS        ResponseError_ErrorCode = 0
	ResponseError_NO_RECORD      ResponseError_ErrorCode = 100
	ResponseError_ERROR_RESPONSE ResponseError_ErrorCode = 101
	ResponseError_CONNECT_FAIL   ResponseError_ErrorCode = 102
	ResponseError_ERROR_ETC      ResponseError_ErrorCode = 103
)

// Enum value maps for ResponseError_ErrorCode.
var (
	ResponseError_ErrorCode_name = map[int32]string{
		0:   "SUCCESS",
		100: "NO_RECORD",
		101: "ERROR_RESPONSE",
		102: "CONNECT_FAIL",
		103: "ERROR_ETC",
	}
	ResponseError_ErrorCode_value = map[string]int32{
		"SUCCESS":        0,
		"NO_RECORD":      100,
		"ERROR_RESPONSE": 101,
		"CONNECT_FAIL":   102,
		"ERROR_ETC":      103,
	}
)

func (x ResponseError_ErrorCode) Enum() *ResponseError_ErrorCode {
	p := new(ResponseError_ErrorCode)
	*p = x
	return p
}

func (x ResponseError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ldap_adapter_v1_proto_enumTypes[1].Descriptor()
}

func (ResponseError_ErrorCode) Type() protoreflect.EnumType {
	return &file_ldap_adapter_v1_proto_enumTypes[1]
}

func (x ResponseError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseError_ErrorCode.Descriptor instead.
func (ResponseError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{3, 1}
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ldap_adapter_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ldap_adapter_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*AuthenticateResponse_Success
	//	*AuthenticateResponse_Error
	Response isAuthenticateResponse_Response `protobuf_oneof:"response"`
	Role     string                          `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ldap_adapter_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ldap_adapter_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{1}
}

func (m *AuthenticateResponse) GetResponse() isAuthenticateResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AuthenticateResponse) GetSuccess() *ResponseSuccess {
	if x, ok := x.GetResponse().(*AuthenticateResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (x *AuthenticateResponse) GetError() *ResponseError {
	if x, ok := x.GetResponse().(*AuthenticateResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *AuthenticateResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type isAuthenticateResponse_Response interface {
	isAuthenticateResponse_Response()
}

type AuthenticateResponse_Success struct {
	Success *ResponseSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type AuthenticateResponse_Error struct {
	Error *ResponseError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AuthenticateResponse_Success) isAuthenticateResponse_Response() {}

func (*AuthenticateResponse_Error) isAuthenticateResponse_Response() {}

type ResponseSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseSuccess) Reset() {
	*x = ResponseSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ldap_adapter_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSuccess) ProtoMessage() {}

func (x *ResponseSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_ldap_adapter_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSuccess.ProtoReflect.Descriptor instead.
func (*ResponseSuccess) Descriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{2}
}

type ResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrpcResponse ResponseError_GrpcResponse `protobuf:"varint,1,opt,name=grpcResponse,proto3,enum=ldap.adapter.v1.ResponseError_GrpcResponse" json:"grpcResponse,omitempty"`
	Code         ResponseError_ErrorCode    `protobuf:"varint,2,opt,name=code,proto3,enum=ldap.adapter.v1.ResponseError_ErrorCode" json:"code,omitempty"`
	Value        string                     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Desc         string                     `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *ResponseError) Reset() {
	*x = ResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ldap_adapter_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseError) ProtoMessage() {}

func (x *ResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_ldap_adapter_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseError.ProtoReflect.Descriptor instead.
func (*ResponseError) Descriptor() ([]byte, []int) {
	return file_ldap_adapter_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseError) GetGrpcResponse() ResponseError_GrpcResponse {
	if x != nil {
		return x.GrpcResponse
	}
	return ResponseError_UNIVERSAL
}

func (x *ResponseError) GetCode() ResponseError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return ResponseError_SUCCESS
}

func (x *ResponseError) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResponseError) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_ldap_adapter_v1_proto protoreflect.FileDescriptor

var file_ldap_adapter_v1_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x41, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x14,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xce, 0x03,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x4f, 0x0a, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x49,
	0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0d, 0x42, 0x41, 0x44, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x10, 0x90, 0x03, 0x12, 0x10, 0x0a, 0x0b,
	0x55, 0x4e, 0x41, 0x55, 0x54, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x91, 0x03, 0x12, 0x0e,
	0x0a, 0x09, 0x46, 0x4f, 0x52, 0x42, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x93, 0x03, 0x12, 0x0e,
	0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x94, 0x03, 0x12, 0x13,
	0x0a, 0x0e, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x96, 0x03, 0x12, 0x11, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0xf4, 0x03, 0x12, 0x18, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0xf7, 0x03,
	0x22, 0x5c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x66, 0x12,
	0x0d, 0x0a, 0x09, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x45, 0x54, 0x43, 0x10, 0x67, 0x32, 0x73,
	0x0a, 0x12, 0x4c, 0x64, 0x61, 0x70, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x6c, 0x64, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x64, 0x61,
	0x70, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x6c, 0x64, 0x61, 0x70, 0x5f, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ldap_adapter_v1_proto_rawDescOnce sync.Once
	file_ldap_adapter_v1_proto_rawDescData = file_ldap_adapter_v1_proto_rawDesc
)

func file_ldap_adapter_v1_proto_rawDescGZIP() []byte {
	file_ldap_adapter_v1_proto_rawDescOnce.Do(func() {
		file_ldap_adapter_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_ldap_adapter_v1_proto_rawDescData)
	})
	return file_ldap_adapter_v1_proto_rawDescData
}

var file_ldap_adapter_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ldap_adapter_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ldap_adapter_v1_proto_goTypes = []interface{}{
	(ResponseError_GrpcResponse)(0), // 0: ldap.adapter.v1.ResponseError.GrpcResponse
	(ResponseError_ErrorCode)(0),    // 1: ldap.adapter.v1.ResponseError.ErrorCode
	(*AuthenticateRequest)(nil),     // 2: ldap.adapter.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),    // 3: ldap.adapter.v1.AuthenticateResponse
	(*ResponseSuccess)(nil),         // 4: ldap.adapter.v1.ResponseSuccess
	(*ResponseError)(nil),           // 5: ldap.adapter.v1.ResponseError
}
var file_ldap_adapter_v1_proto_depIdxs = []int32{
	4, // 0: ldap.adapter.v1.AuthenticateResponse.success:type_name -> ldap.adapter.v1.ResponseSuccess
	5, // 1: ldap.adapter.v1.AuthenticateResponse.error:type_name -> ldap.adapter.v1.ResponseError
	0, // 2: ldap.adapter.v1.ResponseError.grpcResponse:type_name -> ldap.adapter.v1.ResponseError.GrpcResponse
	1, // 3: ldap.adapter.v1.ResponseError.code:type_name -> ldap.adapter.v1.ResponseError.ErrorCode
	2, // 4: ldap.adapter.v1.LdapAdapterService.Authenticate:input_type -> ldap.adapter.v1.AuthenticateRequest
	3, // 5: ldap.adapter.v1.LdapAdapterService.Authenticate:output_type -> ldap.adapter.v1.AuthenticateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ldap_adapter_v1_proto_init() }
func file_ldap_adapter_v1_proto_init() {
	if File_ldap_adapter_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ldap_adapter_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ldap_adapter_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ldap_adapter_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ldap_adapter_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ldap_adapter_v1_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AuthenticateResponse_Success)(nil),
		(*AuthenticateResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ldap_adapter_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ldap_adapter_v1_proto_goTypes,
		DependencyIndexes: file_ldap_adapter_v1_proto_depIdxs,
		EnumInfos:         file_ldap_adapter_v1_proto_enumTypes,
		MessageInfos:      file_ldap_adapter_v1_proto_msgTypes,
	}.Build()
	File_ldap_adapter_v1_proto = out.File
	file_ldap_adapter_v1_proto_rawDesc = nil
	file_ldap_adapter_v1_proto_goTypes = nil
	file_ldap_adapter_v1_proto_depIdxs = nil
}
